
def menu():
    print('***********************************************************')
    print('*        Bem Vindo ao Sistema de Boletim Escolar          *')
    print('***********************************************************')
    print('*              1 - Matricular Aluno                       *')
    print('*              2 - Listar Todos os Alunos                 *')
    print('*              3 - Listar Alunos Aprovados                *')
    print('*              4 - Listar Aluno de Recuperação            *')
    print('*              5 - Listar Aluno Reprovados                *')
    print('*              6 - Buscar Aluno por Matricula             *')
    print('*              7 - Excluir Aluno                          *')
    print('*              8 - Lançar Notas                           *')
    print('*              9 - Listar Notas                           *')
    print('*              10- Excluir Notas                          *')
    print('*              11 - Ver situação do aluno                 *')
    print('*              12 - Atualizar matricula                   *')
    print('*              13- Sair                                   *')
    print('*                                                         *')
    print('***********************************************************')
